### ISSUE TITLE
Clarification on link to Career Seminar

### ISSUE THREAD

**Issue by saltedbones** [TULiberalArts/English#10]
I pulled the link to the career seminar in the format that is used for public policy: 
http://bulletin.temple.edu/search/?P=ENG 1801

It pulls up the career seminar from many career seminars in CLA. Is there a way we can link only to the Career Seminar for English majors?

**Comment by CVE82** [comment]
Link to career seminal blurb on the bulletin http://bulletin.temple.edu/search/?P=ENG%201801

**Comment by saltedbones** [comment]
Yes, but all the other Seminar links are on that page. I want a link to just the English Career Seminar.

**Comment by CVE82** [comment]
Depending on the program, the bulletin doesn't always seperate the courses into single boxes. It depends on how they built the programs into the bulletin. This course doesn't have a separate box and will have those links on the page. Some Economics, Political Science and GUS courses display like this. I submitted a ticket to see if there is another link that we are not aware of.

**Comment by CVE82** [comment]
There isn't another link to link to just the course. The links that are on the page are fine, it let's student's know where this course can count for credit, having the extra information there for them is fine.
