### ISSUE TITLE
Resize Hero Image Por Favor

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/English#11]
Hey Z Dogg when you get a chance tomorrow can you resize the hero? I think I have the resizing system down in Photoshop but don't want to infringe on your area of expertise! =D Thanks!

**Comment by ZMcGroarty** [comment]
![hero_english-min](https://user-images.githubusercontent.com/15017242/39053594-74f8f80c-447d-11e8-9484-ae2efca9e936.png)

**Comment by ZMcGroarty** [comment]
Try this one, it might have a weird white background but let me know how it looks.

**Comment by CVE82** [comment]
Awesome thank you I will try it out now!

**Comment by CVE82** [comment]
@ZMcGroarty check out the home page https://develop.cla.temple.edu/english/ what do you think?

**Comment by ZMcGroarty** [comment]
Meh, lets try this one. In the future we'll have to figure something out for these -- a lot of these pictures are tough!

![hero_english2-min](https://user-images.githubusercontent.com/15017242/39054919-e117ea04-4480-11e8-8894-6243f0c40799.png)

**Comment by CVE82** [comment]
Yes I agree they suck. Thank you for chugging along lol
