### ISSUE TITLE
Missing faculty profiles

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/English#2]
Hello all!,

Does anyone know what happened to the 40 faculty profiles I just committed? Thanks!

**Comment by lidopaglia** [comment]
Should there be more faculty profiles than what was committed in e4f34264befd6e8bfed90337425bae020c57842c?

**Comment by CVE82** [comment]
Good morning, yes I entered and committed the remaining 41 profiles yesterday... I don't know where they went, I definitely commented and hit commit, got the green light, but don't know where they are! =( =( =(

**Comment by lidopaglia** [comment]
hmm. not sure. I see only two commits after https://github.com/TULiberalArts/English/commit/e4f34264befd6e8bfed90337425bae020c57842c. There is  3f4865e1fe2db6fafc3c1e8593adcc6a5c8011ed and 99036f8706217f5a88063d452a616af3dff33a34 but they don't contain what you describe. Were you using prose? We can take a look together today if you're available?

**Comment by tu-chill** [comment]
@camille there are a few places we can look. First place: on github under your profile do you have a repos that were created by your account?

Second place would be to see if the commit was on a branch and not in master. Or is the default branch not master.

C.Hill
Marketing Technology
College of Liberal Arts
Temple University

On Feb 10, 2017, at 8:09 AM, Lido Paglia <notifications@github.com<mailto:notifications@github.com>> wrote:


hmm. not sure. I see only two commits after e4f3426<https://github.com/TULiberalArts/English/commit/e4f34264befd6e8bfed90337425bae020c57842c>. There is 3f4865e<https://github.com/TULiberalArts/English/commit/3f4865e1fe2db6fafc3c1e8593adcc6a5c8011ed> and 99036f8<https://github.com/TULiberalArts/English/commit/99036f8706217f5a88063d452a616af3dff33a34> but they don't contain what you describe. Were you using prose? We can take a look together today if you're available?

-

**Comment by CVE82** [comment]
Hey, no I was using GitHub... I will look at those options with Chris, if we cannot find them I will give you a holler... =)

**Comment by tu-chill** [comment]
This had a very sad ending.
